[package]
name = "Chip8-Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chip8 = { path = "./chip8" }
device_query = "4.0.1"
fastrand = "2.3.0"
itertools = "0.14.0"